### ISSUE TITLE
Missing RFmqtt.o 

### ISSUE THREAD

**Issue by Z1013** [Josar/RandomStuff#3]
Hello Josar,

I've got an error compiling the RPi_utils. The MAKEFILE is as in README.md.
The RFmqtt.o seems so be missing.
`make: *** Keine Regel vorhanden, um das Ziel „RFmqtt.o“,
  benötigt von „RFmqtt“, zu erstellen.  Schluss.
`

Please update the Readme and alter
`sodu make`
to
`sudo make`

Regards Z1013

**Comment by Josar** [comment]
Please compare the make files, seems it changed. Add the required depencies.

```
-lwiringPi -lwiringPiDev -lcrypt
	
```

**Comment by Z1013** [comment]
Hi Josar,

My Mistake, There was a Folder named RFmqtt inside my RPi_Utils and RFmqtt.cpp inside this Folder.
Putting the File in RPi_Utils shows other errors while "making". Correcting these Errors, my RFmqtt.cpp starts now (every include in a seaprate Line, starting with#):

```
....
  by @josar to forward the massages to MQTT */
### #include "../rc-switch/RCSwitch.h"
### #include <stdlib.h>
### #include <stdio.h>
/* usleep */
### #include <unistd.h>
/* nanosleep */
### #include <time.h>
/* for options */
### #include <getopt.h>
#include <strings.h>
/* inlcude MQTT */
### #include <mosquitto.h>
/* parameter
...
```

Everything's fine (RPi 3+ - DietPi, stretch).

Tanks & Regards Z1013
